In [14]:
import pandas as pd
import numpy as nm

In [15]:
df = pd.read_csv('dirty_cafe_sales.csv')

In [16]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9667 non-null   str
 2   Quantity          9862 non-null   str
 3   Price Per Unit    9821 non-null   str
 4   Total Spent       9827 non-null   str
 5   Payment Method    7421 non-null   str
 6   Location          6735 non-null   str
 7   Transaction Date  9841 non-null   str
dtypes: str(8)
memory usage: 1.1 MB

In [18]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [19]:
df.drop_duplicates()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [20]:
df.head(50)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,UNKNOWN,3,3.0,9.0,ERROR,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.0,Cash,UNKNOWN,2023-10-28
8,TXN_4717867,NaN,5,3.0,15.0,NaN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5,4.0,20.0,NaN,In-store,2023-12-31
10,TXN_2548360,Salad,5,5.0,25.0,Cash,Takeaway,2023-11-07
11,TXN_3051279,Sandwich,2,4.0,8.0,Credit Card,Takeaway,ERROR
12,TXN_7619095,Sandwich,2,4.0,8.0,Cash,In-store,2023-05-03
13,TXN_9437049,Cookie,5,1.0,5.0,NaN,Takeaway,2023-06-01
14,TXN_8915701,ERROR,2,1.5,3.0,NaN,In-store,2023-03-21
15,TXN_2847255,Salad,3,5.0,15.0,Credit Card,In-store,2023-11-15
16,TXN_3765707,Sandwich,1,4.0,4.0,NaN,NaN,2023-06-10
17,TXN_6769710,Juice,2,3.0,6.0,Cash,In-store,2023-02-24
18,TXN_8876618,Cake,5,3.0,15.0,Cash,ERROR,2023-03-25
19,TXN_3709394,Juice,4,3.0,12.0,Cash,Takeaway,2023-01-15
20,TXN_3522028,Smoothie,ERROR,4.0,20.0,Cash,In-store,2023-04-04
21,TXN_3567645,Smoothie,4,4.0,16.0,Credit Card,Takeaway,2023-03-30
22,TXN_5132361,Sandwich,3,4.0,12.0,Digital Wallet,Takeaway,2023-12-01
23,TXN_2616390,Sandwich,2,4.0,8.0,NaN,NaN,2023-09-18
24,TXN_9400181,Sandwich,5,4.0,20.0,Cash,In-store,2023-06-03
25,TXN_7958992,Smoothie,3,4.0,NaN,UNKNOWN,UNKNOWN,2023-12-13
26,TXN_5183041,Cookie,5,1.0,5.0,Credit Card,In-store,2023-04-20
27,TXN_5695074,Juice,4,3.0,12.0,Credit Card,Takeaway,2023-04-10
28,TXN_8467949,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-03-11
29,TXN_7640952,Cake,4,3.0,12.0,Digital Wallet,Takeaway,ERROR
30,TXN_1736287,NaN,5,2.0,10.0,Digital Wallet,NaN,2023-06-02
31,TXN_8927252,UNKNOWN,2,1.0,ERROR,Credit Card,ERROR,2023-11-06
32,TXN_9677376,Smoothie,4,4.0,16.0,NaN,In-store,2023-08-15
33,TXN_7710508,UNKNOWN,5,1.0,5.0,Cash,NaN,ERROR
34,TXN_8853997,Smoothie,2,4.0,8.0,Digital Wallet,Takeaway,2023-10-09
35,TXN_9130559,Sandwich,1,4.0,4.0,Credit Card,UNKNOWN,2023-05-28
36,TXN_6855453,UNKNOWN,4,3.0,12.0,NaN,In-store,2023-07-17
37,TXN_1080432,Salad,2,5.0,10.0,Credit Card,In-store,2023-04-29
38,TXN_2655815,Smoothie,4,4.0,16.0,NaN,Takeaway,2023-06-08
39,TXN_6688524,Coffee,4,2.0,8.0,ERROR,NaN,2023-06-29
40,TXN_2083138,Smoothie,3,4.0,12.0,NaN,In-store,2023-04-17
41,TXN_2427584,Sandwich,4,4.0,16.0,NaN,Takeaway,2023-12-22
42,TXN_6650263,Tea,2,1.5,UNKNOWN,NaN,Takeaway,2023-01-10
43,TXN_9620080,Juice,4,3.0,12.0,NaN,Takeaway,2023-10-02
44,TXN_1491578,Cookie,2,1.0,2.0,NaN,NaN,2023-02-23
45,TXN_5455792,Salad,3,5.0,15.0,Cash,NaN,2023-03-22
46,TXN_8078640,Juice,4,3.0,12.0,Digital Wallet,In-store,2023-11-03
47,TXN_9499313,Juice,5,3.0,15.0,NaN,NaN,2023-03-02
48,TXN_8201146,Juice,5,3.0,15.0,Cash,NaN,2023-06-26
49,TXN_8230936,Cake,3,3.0,9.0,NaN,ERROR,2023-05-02

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9667 non-null   str
 2   Quantity          9862 non-null   str
 3   Price Per Unit    9821 non-null   str
 4   Total Spent       9827 non-null   str
 5   Payment Method    7421 non-null   str
 6   Location          6735 non-null   str
 7   Transaction Date  9841 non-null   str
dtypes: str(8)
memory usage: 1.1 MB

In [22]:
df.shape

(10000, 8)

In [23]:
df.describe()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
count,10000,9667,9862,9821,9827,7421,6735,9841
unique,10000,10,7,8,19,5,4,367
top,TXN_1961373,Juice,5,3.0,6.0,Digital Wallet,Takeaway,UNKNOWN
freq,1,1171,2013,2429,979,2291,3022,159

In [24]:
df['Item'].isnull().sum()

np.int64(333)

In [25]:
df.isnull().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [26]:
df.isin(["UNKNOWN", "ERROR","NaN"]).sum()

Transaction ID        0
Item                636
Quantity            341
Price Per Unit      354
Total Spent         329
Payment Method      599
Location            696
Transaction Date    301
dtype: int64

In [27]:
df = df.replace(["UNKNOWN", "ERROR","NaN"], nm.nan)

In [28]:
df.head(50)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,NaN,NaN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,NaN,3,3.0,9.0,NaN,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.0,Cash,NaN,2023-10-28
8,TXN_4717867,NaN,5,3.0,15.0,NaN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5,4.0,20.0,NaN,In-store,2023-12-31
10,TXN_2548360,Salad,5,5.0,25.0,Cash,Takeaway,2023-11-07
11,TXN_3051279,Sandwich,2,4.0,8.0,Credit Card,Takeaway,NaN
12,TXN_7619095,Sandwich,2,4.0,8.0,Cash,In-store,2023-05-03
13,TXN_9437049,Cookie,5,1.0,5.0,NaN,Takeaway,2023-06-01
14,TXN_8915701,NaN,2,1.5,3.0,NaN,In-store,2023-03-21
15,TXN_2847255,Salad,3,5.0,15.0,Credit Card,In-store,2023-11-15
16,TXN_3765707,Sandwich,1,4.0,4.0,NaN,NaN,2023-06-10
17,TXN_6769710,Juice,2,3.0,6.0,Cash,In-store,2023-02-24
18,TXN_8876618,Cake,5,3.0,15.0,Cash,NaN,2023-03-25
19,TXN_3709394,Juice,4,3.0,12.0,Cash,Takeaway,2023-01-15
20,TXN_3522028,Smoothie,NaN,4.0,20.0,Cash,In-store,2023-04-04
21,TXN_3567645,Smoothie,4,4.0,16.0,Credit Card,Takeaway,2023-03-30
22,TXN_5132361,Sandwich,3,4.0,12.0,Digital Wallet,Takeaway,2023-12-01
23,TXN_2616390,Sandwich,2,4.0,8.0,NaN,NaN,2023-09-18
24,TXN_9400181,Sandwich,5,4.0,20.0,Cash,In-store,2023-06-03
25,TXN_7958992,Smoothie,3,4.0,NaN,NaN,NaN,2023-12-13
26,TXN_5183041,Cookie,5,1.0,5.0,Credit Card,In-store,2023-04-20
27,TXN_5695074,Juice,4,3.0,12.0,Credit Card,Takeaway,2023-04-10
28,TXN_8467949,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-03-11
29,TXN_7640952,Cake,4,3.0,12.0,Digital Wallet,Takeaway,NaN
30,TXN_1736287,NaN,5,2.0,10.0,Digital Wallet,NaN,2023-06-02
31,TXN_8927252,NaN,2,1.0,NaN,Credit Card,NaN,2023-11-06
32,TXN_9677376,Smoothie,4,4.0,16.0,NaN,In-store,2023-08-15
33,TXN_7710508,NaN,5,1.0,5.0,Cash,NaN,NaN
34,TXN_8853997,Smoothie,2,4.0,8.0,Digital Wallet,Takeaway,2023-10-09
35,TXN_9130559,Sandwich,1,4.0,4.0,Credit Card,NaN,2023-05-28
36,TXN_6855453,NaN,4,3.0,12.0,NaN,In-store,2023-07-17
37,TXN_1080432,Salad,2,5.0,10.0,Credit Card,In-store,2023-04-29
38,TXN_2655815,Smoothie,4,4.0,16.0,NaN,Takeaway,2023-06-08
39,TXN_6688524,Coffee,4,2.0,8.0,NaN,NaN,2023-06-29
40,TXN_2083138,Smoothie,3,4.0,12.0,NaN,In-store,2023-04-17
41,TXN_2427584,Sandwich,4,4.0,16.0,NaN,Takeaway,2023-12-22
42,TXN_6650263,Tea,2,1.5,NaN,NaN,Takeaway,2023-01-10
43,TXN_9620080,Juice,4,3.0,12.0,NaN,Takeaway,2023-10-02
44,TXN_1491578,Cookie,2,1.0,2.0,NaN,NaN,2023-02-23
45,TXN_5455792,Salad,3,5.0,15.0,Cash,NaN,2023-03-22
46,TXN_8078640,Juice,4,3.0,12.0,Digital Wallet,In-store,2023-11-03
47,TXN_9499313,Juice,5,3.0,15.0,NaN,NaN,2023-03-02
48,TXN_8201146,Juice,5,3.0,15.0,Cash,NaN,2023-06-26
49,TXN_8230936,Cake,3,3.0,9.0,NaN,NaN,2023-05-02

In [29]:
df.isnull().sum()

Transaction ID         0
Item                 969
Quantity             479
Price Per Unit       533
Total Spent          502
Payment Method      3178
Location            3961
Transaction Date     460
dtype: int64

In [30]:
numeric_cols = ["Quantity", "Price Per Unit" , "Total Spent"]
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

In [31]:
df.head(50)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,NaN,NaN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5.0,4.0,20.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,NaN,3.0,3.0,9.0,NaN,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4.0,4.0,16.0,Cash,NaN,2023-10-28
8,TXN_4717867,NaN,5.0,3.0,15.0,NaN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5.0,4.0,20.0,NaN,In-store,2023-12-31
10,TXN_2548360,Salad,5.0,5.0,25.0,Cash,Takeaway,2023-11-07
11,TXN_3051279,Sandwich,2.0,4.0,8.0,Credit Card,Takeaway,NaN
12,TXN_7619095,Sandwich,2.0,4.0,8.0,Cash,In-store,2023-05-03
13,TXN_9437049,Cookie,5.0,1.0,5.0,NaN,Takeaway,2023-06-01
14,TXN_8915701,NaN,2.0,1.5,3.0,NaN,In-store,2023-03-21
15,TXN_2847255,Salad,3.0,5.0,15.0,Credit Card,In-store,2023-11-15
16,TXN_3765707,Sandwich,1.0,4.0,4.0,NaN,NaN,2023-06-10
17,TXN_6769710,Juice,2.0,3.0,6.0,Cash,In-store,2023-02-24
18,TXN_8876618,Cake,5.0,3.0,15.0,Cash,NaN,2023-03-25
19,TXN_3709394,Juice,4.0,3.0,12.0,Cash,Takeaway,2023-01-15
20,TXN_3522028,Smoothie,NaN,4.0,20.0,Cash,In-store,2023-04-04
21,TXN_3567645,Smoothie,4.0,4.0,16.0,Credit Card,Takeaway,2023-03-30
22,TXN_5132361,Sandwich,3.0,4.0,12.0,Digital Wallet,Takeaway,2023-12-01
23,TXN_2616390,Sandwich,2.0,4.0,8.0,NaN,NaN,2023-09-18
24,TXN_9400181,Sandwich,5.0,4.0,20.0,Cash,In-store,2023-06-03
25,TXN_7958992,Smoothie,3.0,4.0,NaN,NaN,NaN,2023-12-13
26,TXN_5183041,Cookie,5.0,1.0,5.0,Credit Card,In-store,2023-04-20
27,TXN_5695074,Juice,4.0,3.0,12.0,Credit Card,Takeaway,2023-04-10
28,TXN_8467949,Smoothie,5.0,4.0,20.0,Credit Card,NaN,2023-03-11
29,TXN_7640952,Cake,4.0,3.0,12.0,Digital Wallet,Takeaway,NaN
30,TXN_1736287,NaN,5.0,2.0,10.0,Digital Wallet,NaN,2023-06-02
31,TXN_8927252,NaN,2.0,1.0,NaN,Credit Card,NaN,2023-11-06
32,TXN_9677376,Smoothie,4.0,4.0,16.0,NaN,In-store,2023-08-15
33,TXN_7710508,NaN,5.0,1.0,5.0,Cash,NaN,NaN
34,TXN_8853997,Smoothie,2.0,4.0,8.0,Digital Wallet,Takeaway,2023-10-09
35,TXN_9130559,Sandwich,1.0,4.0,4.0,Credit Card,NaN,2023-05-28
36,TXN_6855453,NaN,4.0,3.0,12.0,NaN,In-store,2023-07-17
37,TXN_1080432,Salad,2.0,5.0,10.0,Credit Card,In-store,2023-04-29
38,TXN_2655815,Smoothie,4.0,4.0,16.0,NaN,Takeaway,2023-06-08
39,TXN_6688524,Coffee,4.0,2.0,8.0,NaN,NaN,2023-06-29
40,TXN_2083138,Smoothie,3.0,4.0,12.0,NaN,In-store,2023-04-17
41,TXN_2427584,Sandwich,4.0,4.0,16.0,NaN,Takeaway,2023-12-22
42,TXN_6650263,Tea,2.0,1.5,NaN,NaN,Takeaway,2023-01-10
43,TXN_9620080,Juice,4.0,3.0,12.0,NaN,Takeaway,2023-10-02
44,TXN_1491578,Cookie,2.0,1.0,2.0,NaN,NaN,2023-02-23
45,TXN_5455792,Salad,3.0,5.0,15.0,Cash,NaN,2023-03-22
46,TXN_8078640,Juice,4.0,3.0,12.0,Digital Wallet,In-store,2023-11-03
47,TXN_9499313,Juice,5.0,3.0,15.0,NaN,NaN,2023-03-02
48,TXN_8201146,Juice,5.0,3.0,15.0,Cash,NaN,2023-06-26
49,TXN_8230936,Cake,3.0,3.0,9.0,NaN,NaN,2023-05-02

In [32]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9031 non-null   str
 2   Quantity          9521 non-null   float64
 3   Price Per Unit    9467 non-null   float64
 4   Total Spent       9498 non-null   float64
 5   Payment Method    6822 non-null   str
 6   Location          6039 non-null   str
 7   Transaction Date  9540 non-null   str
dtypes: float64(3), str(5)
memory usage: 991.9 KB

In [33]:
df[["Quantity", "Price Per Unit", "Total Spent"]].describe()

          Quantity  Price Per Unit  Total Spent
count  9521.000000     9467.000000  9498.000000
mean      3.028463        2.949984     8.924352
std       1.419007        1.278450     6.009919
min       1.000000        1.000000     1.000000
25%       2.000000        2.000000     4.000000
50%       3.000000        3.000000     8.000000
75%       4.000000        4.000000    12.000000
max       5.000000        5.000000    25.000000

In [34]:
df["Calculated Total"] = (
    df["Quantity"] * df["Price Per Unit"]
)

In [35]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9031 non-null   str
 2   Quantity          9521 non-null   float64
 3   Price Per Unit    9467 non-null   float64
 4   Total Spent       9498 non-null   float64
 5   Payment Method    6822 non-null   str
 6   Location          6039 non-null   str
 7   Transaction Date  9540 non-null   str
 8   Calculated Total  9006 non-null   float64
dtypes: float64(4), str(5)
memory usage: 1.0 MB

In [36]:
df["Transaction Date"] = pd.to_datetime(
    df["Transaction Date"],
    errors="coerce"
)

In [37]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9031 non-null   str
 2   Quantity          9521 non-null   float64
 3   Price Per Unit    9467 non-null   float64
 4   Total Spent       9498 non-null   float64
 5   Payment Method    6822 non-null   str
 6   Location          6039 non-null   str
 7   Transaction Date  9540 non-null   datetime64[us]
 8   Calculated Total  9006 non-null   float64
dtypes: datetime64[us](1), float64(4), str(4)
memory usage: 975.7 KB

In [38]:
df["Transaction Date"].dtype

dtype('<M8[us]')

In [39]:
print(df["Transaction Date"].dtype)

datetime64[us]

In [40]:
df.duplicated().sum()

np.int64(0)

In [41]:
print("Quantity zero or below:")
print((df["Quantity"] <= 0).sum())

print("Price zero or below:")
print((df["Price Per Unit"] <= 0).sum())

print("Price zero or below:")
print((df["Total Spent"] <= 0).sum())

Quantity zero or below:
0
Price zero or below:
0
Price zero or below:
0

In [42]:
df["Calculated Total"] = (
    df["Quantity"] * df["Price Per Unit"]
)

In [43]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Calculated Total
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08,4.0
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16,12.0
2,TXN_4271903,Cookie,4.0,1.0,NaN,Credit Card,In-store,2023-07-19,4.0
3,TXN_7034554,Salad,2.0,5.0,10.0,NaN,NaN,2023-04-27,10.0
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11,4.0

In [44]:
text_cols = ["Item", "Payment Method", "Location"]

for col in text_cols:
    df[col] = df[col].str.strip()

In [45]:
df.head(50)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Calculated Total
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08,4.0
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16,12.0
2,TXN_4271903,Cookie,4.0,1.0,NaN,Credit Card,In-store,2023-07-19,4.0
3,TXN_7034554,Salad,2.0,5.0,10.0,NaN,NaN,2023-04-27,10.0
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11,4.0
5,TXN_2602893,Smoothie,5.0,4.0,20.0,Credit Card,NaN,2023-03-31,20.0
6,TXN_4433211,NaN,3.0,3.0,9.0,NaN,Takeaway,2023-10-06,9.0
7,TXN_6699534,Sandwich,4.0,4.0,16.0,Cash,NaN,2023-10-28,16.0
8,TXN_4717867,NaN,5.0,3.0,15.0,NaN,Takeaway,2023-07-28,15.0
9,TXN_2064365,Sandwich,5.0,4.0,20.0,NaN,In-store,2023-12-31,20.0
10,TXN_2548360,Salad,5.0,5.0,25.0,Cash,Takeaway,2023-11-07,25.0
11,TXN_3051279,Sandwich,2.0,4.0,8.0,Credit Card,Takeaway,NaT,8.0
12,TXN_7619095,Sandwich,2.0,4.0,8.0,Cash,In-store,2023-05-03,8.0
13,TXN_9437049,Cookie,5.0,1.0,5.0,NaN,Takeaway,2023-06-01,5.0
14,TXN_8915701,NaN,2.0,1.5,3.0,NaN,In-store,2023-03-21,3.0
15,TXN_2847255,Salad,3.0,5.0,15.0,Credit Card,In-store,2023-11-15,15.0
16,TXN_3765707,Sandwich,1.0,4.0,4.0,NaN,NaN,2023-06-10,4.0
17,TXN_6769710,Juice,2.0,3.0,6.0,Cash,In-store,2023-02-24,6.0
18,TXN_8876618,Cake,5.0,3.0,15.0,Cash,NaN,2023-03-25,15.0
19,TXN_3709394,Juice,4.0,3.0,12.0,Cash,Takeaway,2023-01-15,12.0
20,TXN_3522028,Smoothie,NaN,4.0,20.0,Cash,In-store,2023-04-04,NaN
21,TXN_3567645,Smoothie,4.0,4.0,16.0,Credit Card,Takeaway,2023-03-30,16.0
22,TXN_5132361,Sandwich,3.0,4.0,12.0,Digital Wallet,Takeaway,2023-12-01,12.0
23,TXN_2616390,Sandwich,2.0,4.0,8.0,NaN,NaN,2023-09-18,8.0
24,TXN_9400181,Sandwich,5.0,4.0,20.0,Cash,In-store,2023-06-03,20.0
25,TXN_7958992,Smoothie,3.0,4.0,NaN,NaN,NaN,2023-12-13,12.0
26,TXN_5183041,Cookie,5.0,1.0,5.0,Credit Card,In-store,2023-04-20,5.0
27,TXN_5695074,Juice,4.0,3.0,12.0,Credit Card,Takeaway,2023-04-10,12.0
28,TXN_8467949,Smoothie,5.0,4.0,20.0,Credit Card,NaN,2023-03-11,20.0
29,TXN_7640952,Cake,4.0,3.0,12.0,Digital Wallet,Takeaway,NaT,12.0
30,TXN_1736287,NaN,5.0,2.0,10.0,Digital Wallet,NaN,2023-06-02,10.0
31,TXN_8927252,NaN,2.0,1.0,NaN,Credit Card,NaN,2023-11-06,2.0
32,TXN_9677376,Smoothie,4.0,4.0,16.0,NaN,In-store,2023-08-15,16.0
33,TXN_7710508,NaN,5.0,1.0,5.0,Cash,NaN,NaT,5.0
34,TXN_8853997,Smoothie,2.0,4.0,8.0,Digital Wallet,Takeaway,2023-10-09,8.0
35,TXN_9130559,Sandwich,1.0,4.0,4.0,Credit Card,NaN,2023-05-28,4.0
36,TXN_6855453,NaN,4.0,3.0,12.0,NaN,In-store,2023-07-17,12.0
37,TXN_1080432,Salad,2.0,5.0,10.0,Credit Card,In-store,2023-04-29,10.0
38,TXN_2655815,Smoothie,4.0,4.0,16.0,NaN,Takeaway,2023-06-08,16.0
39,TXN_6688524,Coffee,4.0,2.0,8.0,NaN,NaN,2023-06-29,8.0
40,TXN_2083138,Smoothie,3.0,4.0,12.0,NaN,In-store,2023-04-17,12.0
41,TXN_2427584,Sandwich,4.0,4.0,16.0,NaN,Takeaway,2023-12-22,16.0
42,TXN_6650263,Tea,2.0,1.5,NaN,NaN,Takeaway,2023-01-10,3.0
43,TXN_9620080,Juice,4.0,3.0,12.0,NaN,Takeaway,2023-10-02,12.0
44,TXN_1491578,Cookie,2.0,1.0,2.0,NaN,NaN,2023-02-23,2.0
45,TXN_5455792,Salad,3.0,5.0,15.0,Cash,NaN,2023-03-22,15.0
46,TXN_8078640,Juice,4.0,3.0,12.0,Digital Wallet,In-store,2023-11-03,12.0
47,TXN_9499313,Juice,5.0,3.0,15.0,NaN,NaN,2023-03-02,15.0
48,TXN_8201146,Juice,5.0,3.0,15.0,Cash,NaN,2023-06-26,15.0
49,TXN_8230936,Cake,3.0,3.0,9.0,NaN,NaN,2023-05-02,9.0

In [46]:
df["Month"] = df["Transaction Date"].dt.month_name()

In [47]:
df.head(50)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Calculated Total,Month
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08,4.0,September
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16,12.0,May
2,TXN_4271903,Cookie,4.0,1.0,NaN,Credit Card,In-store,2023-07-19,4.0,July
3,TXN_7034554,Salad,2.0,5.0,10.0,NaN,NaN,2023-04-27,10.0,April
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11,4.0,June
5,TXN_2602893,Smoothie,5.0,4.0,20.0,Credit Card,NaN,2023-03-31,20.0,March
6,TXN_4433211,NaN,3.0,3.0,9.0,NaN,Takeaway,2023-10-06,9.0,October
7,TXN_6699534,Sandwich,4.0,4.0,16.0,Cash,NaN,2023-10-28,16.0,October
8,TXN_4717867,NaN,5.0,3.0,15.0,NaN,Takeaway,2023-07-28,15.0,July
9,TXN_2064365,Sandwich,5.0,4.0,20.0,NaN,In-store,2023-12-31,20.0,December
10,TXN_2548360,Salad,5.0,5.0,25.0,Cash,Takeaway,2023-11-07,25.0,November
11,TXN_3051279,Sandwich,2.0,4.0,8.0,Credit Card,Takeaway,NaT,8.0,NaN
12,TXN_7619095,Sandwich,2.0,4.0,8.0,Cash,In-store,2023-05-03,8.0,May
13,TXN_9437049,Cookie,5.0,1.0,5.0,NaN,Takeaway,2023-06-01,5.0,June
14,TXN_8915701,NaN,2.0,1.5,3.0,NaN,In-store,2023-03-21,3.0,March
15,TXN_2847255,Salad,3.0,5.0,15.0,Credit Card,In-store,2023-11-15,15.0,November
16,TXN_3765707,Sandwich,1.0,4.0,4.0,NaN,NaN,2023-06-10,4.0,June
17,TXN_6769710,Juice,2.0,3.0,6.0,Cash,In-store,2023-02-24,6.0,February
18,TXN_8876618,Cake,5.0,3.0,15.0,Cash,NaN,2023-03-25,15.0,March
19,TXN_3709394,Juice,4.0,3.0,12.0,Cash,Takeaway,2023-01-15,12.0,January
20,TXN_3522028,Smoothie,NaN,4.0,20.0,Cash,In-store,2023-04-04,NaN,April
21,TXN_3567645,Smoothie,4.0,4.0,16.0,Credit Card,Takeaway,2023-03-30,16.0,March
22,TXN_5132361,Sandwich,3.0,4.0,12.0,Digital Wallet,Takeaway,2023-12-01,12.0,December
23,TXN_2616390,Sandwich,2.0,4.0,8.0,NaN,NaN,2023-09-18,8.0,September
24,TXN_9400181,Sandwich,5.0,4.0,20.0,Cash,In-store,2023-06-03,20.0,June
25,TXN_7958992,Smoothie,3.0,4.0,NaN,NaN,NaN,2023-12-13,12.0,December
26,TXN_5183041,Cookie,5.0,1.0,5.0,Credit Card,In-store,2023-04-20,5.0,April
27,TXN_5695074,Juice,4.0,3.0,12.0,Credit Card,Takeaway,2023-04-10,12.0,April
28,TXN_8467949,Smoothie,5.0,4.0,20.0,Credit Card,NaN,2023-03-11,20.0,March
29,TXN_7640952,Cake,4.0,3.0,12.0,Digital Wallet,Takeaway,NaT,12.0,NaN
30,TXN_1736287,NaN,5.0,2.0,10.0,Digital Wallet,NaN,2023-06-02,10.0,June
31,TXN_8927252,NaN,2.0,1.0,NaN,Credit Card,NaN,2023-11-06,2.0,November
32,TXN_9677376,Smoothie,4.0,4.0,16.0,NaN,In-store,2023-08-15,16.0,August
33,TXN_7710508,NaN,5.0,1.0,5.0,Cash,NaN,NaT,5.0,NaN
34,TXN_8853997,Smoothie,2.0,4.0,8.0,Digital Wallet,Takeaway,2023-10-09,8.0,October
35,TXN_9130559,Sandwich,1.0,4.0,4.0,Credit Card,NaN,2023-05-28,4.0,May
36,TXN_6855453,NaN,4.0,3.0,12.0,NaN,In-store,2023-07-17,12.0,July
37,TXN_1080432,Salad,2.0,5.0,10.0,Credit Card,In-store,2023-04-29,10.0,April
38,TXN_2655815,Smoothie,4.0,4.0,16.0,NaN,Takeaway,2023-06-08,16.0,June
39,TXN_6688524,Coffee,4.0,2.0,8.0,NaN,NaN,2023-06-29,8.0,June
40,TXN_2083138,Smoothie,3.0,4.0,12.0,NaN,In-store,2023-04-17,12.0,April
41,TXN_2427584,Sandwich,4.0,4.0,16.0,NaN,Takeaway,2023-12-22,16.0,December
42,TXN_6650263,Tea,2.0,1.5,NaN,NaN,Takeaway,2023-01-10,3.0,January
43,TXN_9620080,Juice,4.0,3.0,12.0,NaN,Takeaway,2023-10-02,12.0,October
44,TXN_1491578,Cookie,2.0,1.0,2.0,NaN,NaN,2023-02-23,2.0,February
45,TXN_5455792,Salad,3.0,5.0,15.0,Cash,NaN,2023-03-22,15.0,March
46,TXN_8078640,Juice,4.0,3.0,12.0,Digital Wallet,In-store,2023-11-03,12.0,November
47,TXN_9499313,Juice,5.0,3.0,15.0,NaN,NaN,2023-03-02,15.0,March
48,TXN_8201146,Juice,5.0,3.0,15.0,Cash,NaN,2023-06-26,15.0,June
49,TXN_8230936,Cake,3.0,3.0,9.0,NaN,NaN,2023-05-02,9.0,May

In [48]:
df["Total Spent"] = df["Total Spent"].fillna(
    df["Calculated Total"]
)

In [49]:
df.head(50)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Calculated Total,Month
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08,4.0,September
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16,12.0,May
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,In-store,2023-07-19,4.0,July
3,TXN_7034554,Salad,2.0,5.0,10.0,NaN,NaN,2023-04-27,10.0,April
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11,4.0,June
5,TXN_2602893,Smoothie,5.0,4.0,20.0,Credit Card,NaN,2023-03-31,20.0,March
6,TXN_4433211,NaN,3.0,3.0,9.0,NaN,Takeaway,2023-10-06,9.0,October
7,TXN_6699534,Sandwich,4.0,4.0,16.0,Cash,NaN,2023-10-28,16.0,October
8,TXN_4717867,NaN,5.0,3.0,15.0,NaN,Takeaway,2023-07-28,15.0,July
9,TXN_2064365,Sandwich,5.0,4.0,20.0,NaN,In-store,2023-12-31,20.0,December
10,TXN_2548360,Salad,5.0,5.0,25.0,Cash,Takeaway,2023-11-07,25.0,November
11,TXN_3051279,Sandwich,2.0,4.0,8.0,Credit Card,Takeaway,NaT,8.0,NaN
12,TXN_7619095,Sandwich,2.0,4.0,8.0,Cash,In-store,2023-05-03,8.0,May
13,TXN_9437049,Cookie,5.0,1.0,5.0,NaN,Takeaway,2023-06-01,5.0,June
14,TXN_8915701,NaN,2.0,1.5,3.0,NaN,In-store,2023-03-21,3.0,March
15,TXN_2847255,Salad,3.0,5.0,15.0,Credit Card,In-store,2023-11-15,15.0,November
16,TXN_3765707,Sandwich,1.0,4.0,4.0,NaN,NaN,2023-06-10,4.0,June
17,TXN_6769710,Juice,2.0,3.0,6.0,Cash,In-store,2023-02-24,6.0,February
18,TXN_8876618,Cake,5.0,3.0,15.0,Cash,NaN,2023-03-25,15.0,March
19,TXN_3709394,Juice,4.0,3.0,12.0,Cash,Takeaway,2023-01-15,12.0,January
20,TXN_3522028,Smoothie,NaN,4.0,20.0,Cash,In-store,2023-04-04,NaN,April
21,TXN_3567645,Smoothie,4.0,4.0,16.0,Credit Card,Takeaway,2023-03-30,16.0,March
22,TXN_5132361,Sandwich,3.0,4.0,12.0,Digital Wallet,Takeaway,2023-12-01,12.0,December
23,TXN_2616390,Sandwich,2.0,4.0,8.0,NaN,NaN,2023-09-18,8.0,September
24,TXN_9400181,Sandwich,5.0,4.0,20.0,Cash,In-store,2023-06-03,20.0,June
25,TXN_7958992,Smoothie,3.0,4.0,12.0,NaN,NaN,2023-12-13,12.0,December
26,TXN_5183041,Cookie,5.0,1.0,5.0,Credit Card,In-store,2023-04-20,5.0,April
27,TXN_5695074,Juice,4.0,3.0,12.0,Credit Card,Takeaway,2023-04-10,12.0,April
28,TXN_8467949,Smoothie,5.0,4.0,20.0,Credit Card,NaN,2023-03-11,20.0,March
29,TXN_7640952,Cake,4.0,3.0,12.0,Digital Wallet,Takeaway,NaT,12.0,NaN
30,TXN_1736287,NaN,5.0,2.0,10.0,Digital Wallet,NaN,2023-06-02,10.0,June
31,TXN_8927252,NaN,2.0,1.0,2.0,Credit Card,NaN,2023-11-06,2.0,November
32,TXN_9677376,Smoothie,4.0,4.0,16.0,NaN,In-store,2023-08-15,16.0,August
33,TXN_7710508,NaN,5.0,1.0,5.0,Cash,NaN,NaT,5.0,NaN
34,TXN_8853997,Smoothie,2.0,4.0,8.0,Digital Wallet,Takeaway,2023-10-09,8.0,October
35,TXN_9130559,Sandwich,1.0,4.0,4.0,Credit Card,NaN,2023-05-28,4.0,May
36,TXN_6855453,NaN,4.0,3.0,12.0,NaN,In-store,2023-07-17,12.0,July
37,TXN_1080432,Salad,2.0,5.0,10.0,Credit Card,In-store,2023-04-29,10.0,April
38,TXN_2655815,Smoothie,4.0,4.0,16.0,NaN,Takeaway,2023-06-08,16.0,June
39,TXN_6688524,Coffee,4.0,2.0,8.0,NaN,NaN,2023-06-29,8.0,June
40,TXN_2083138,Smoothie,3.0,4.0,12.0,NaN,In-store,2023-04-17,12.0,April
41,TXN_2427584,Sandwich,4.0,4.0,16.0,NaN,Takeaway,2023-12-22,16.0,December
42,TXN_6650263,Tea,2.0,1.5,3.0,NaN,Takeaway,2023-01-10,3.0,January
43,TXN_9620080,Juice,4.0,3.0,12.0,NaN,Takeaway,2023-10-02,12.0,October
44,TXN_1491578,Cookie,2.0,1.0,2.0,NaN,NaN,2023-02-23,2.0,February
45,TXN_5455792,Salad,3.0,5.0,15.0,Cash,NaN,2023-03-22,15.0,March
46,TXN_8078640,Juice,4.0,3.0,12.0,Digital Wallet,In-store,2023-11-03,12.0,November
47,TXN_9499313,Juice,5.0,3.0,15.0,NaN,NaN,2023-03-02,15.0,March
48,TXN_8201146,Juice,5.0,3.0,15.0,Cash,NaN,2023-06-26,15.0,June
49,TXN_8230936,Cake,3.0,3.0,9.0,NaN,NaN,2023-05-02,9.0,May

In [51]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9031 non-null   str
 2   Quantity          9521 non-null   float64
 3   Price Per Unit    9467 non-null   float64
 4   Total Spent       9960 non-null   float64
 5   Payment Method    6822 non-null   str
 6   Location          6039 non-null   str
 7   Transaction Date  9540 non-null   datetime64[us]
 8   Calculated Total  9006 non-null   float64
 9   Month             9540 non-null   str
dtypes: datetime64[us](1), float64(4), str(5)
memory usage: 1.1 MB

In [52]:
df = df.drop(columns=["Calculated Total"])

In [53]:
df.head(50)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Month
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08,September
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16,May
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,In-store,2023-07-19,July
3,TXN_7034554,Salad,2.0,5.0,10.0,NaN,NaN,2023-04-27,April
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11,June
5,TXN_2602893,Smoothie,5.0,4.0,20.0,Credit Card,NaN,2023-03-31,March
6,TXN_4433211,NaN,3.0,3.0,9.0,NaN,Takeaway,2023-10-06,October
7,TXN_6699534,Sandwich,4.0,4.0,16.0,Cash,NaN,2023-10-28,October
8,TXN_4717867,NaN,5.0,3.0,15.0,NaN,Takeaway,2023-07-28,July
9,TXN_2064365,Sandwich,5.0,4.0,20.0,NaN,In-store,2023-12-31,December
10,TXN_2548360,Salad,5.0,5.0,25.0,Cash,Takeaway,2023-11-07,November
11,TXN_3051279,Sandwich,2.0,4.0,8.0,Credit Card,Takeaway,NaT,NaN
12,TXN_7619095,Sandwich,2.0,4.0,8.0,Cash,In-store,2023-05-03,May
13,TXN_9437049,Cookie,5.0,1.0,5.0,NaN,Takeaway,2023-06-01,June
14,TXN_8915701,NaN,2.0,1.5,3.0,NaN,In-store,2023-03-21,March
15,TXN_2847255,Salad,3.0,5.0,15.0,Credit Card,In-store,2023-11-15,November
16,TXN_3765707,Sandwich,1.0,4.0,4.0,NaN,NaN,2023-06-10,June
17,TXN_6769710,Juice,2.0,3.0,6.0,Cash,In-store,2023-02-24,February
18,TXN_8876618,Cake,5.0,3.0,15.0,Cash,NaN,2023-03-25,March
19,TXN_3709394,Juice,4.0,3.0,12.0,Cash,Takeaway,2023-01-15,January
20,TXN_3522028,Smoothie,NaN,4.0,20.0,Cash,In-store,2023-04-04,April
21,TXN_3567645,Smoothie,4.0,4.0,16.0,Credit Card,Takeaway,2023-03-30,March
22,TXN_5132361,Sandwich,3.0,4.0,12.0,Digital Wallet,Takeaway,2023-12-01,December
23,TXN_2616390,Sandwich,2.0,4.0,8.0,NaN,NaN,2023-09-18,September
24,TXN_9400181,Sandwich,5.0,4.0,20.0,Cash,In-store,2023-06-03,June
25,TXN_7958992,Smoothie,3.0,4.0,12.0,NaN,NaN,2023-12-13,December
26,TXN_5183041,Cookie,5.0,1.0,5.0,Credit Card,In-store,2023-04-20,April
27,TXN_5695074,Juice,4.0,3.0,12.0,Credit Card,Takeaway,2023-04-10,April
28,TXN_8467949,Smoothie,5.0,4.0,20.0,Credit Card,NaN,2023-03-11,March
29,TXN_7640952,Cake,4.0,3.0,12.0,Digital Wallet,Takeaway,NaT,NaN
30,TXN_1736287,NaN,5.0,2.0,10.0,Digital Wallet,NaN,2023-06-02,June
31,TXN_8927252,NaN,2.0,1.0,2.0,Credit Card,NaN,2023-11-06,November
32,TXN_9677376,Smoothie,4.0,4.0,16.0,NaN,In-store,2023-08-15,August
33,TXN_7710508,NaN,5.0,1.0,5.0,Cash,NaN,NaT,NaN
34,TXN_8853997,Smoothie,2.0,4.0,8.0,Digital Wallet,Takeaway,2023-10-09,October
35,TXN_9130559,Sandwich,1.0,4.0,4.0,Credit Card,NaN,2023-05-28,May
36,TXN_6855453,NaN,4.0,3.0,12.0,NaN,In-store,2023-07-17,July
37,TXN_1080432,Salad,2.0,5.0,10.0,Credit Card,In-store,2023-04-29,April
38,TXN_2655815,Smoothie,4.0,4.0,16.0,NaN,Takeaway,2023-06-08,June
39,TXN_6688524,Coffee,4.0,2.0,8.0,NaN,NaN,2023-06-29,June
40,TXN_2083138,Smoothie,3.0,4.0,12.0,NaN,In-store,2023-04-17,April
41,TXN_2427584,Sandwich,4.0,4.0,16.0,NaN,Takeaway,2023-12-22,December
42,TXN_6650263,Tea,2.0,1.5,3.0,NaN,Takeaway,2023-01-10,January
43,TXN_9620080,Juice,4.0,3.0,12.0,NaN,Takeaway,2023-10-02,October
44,TXN_1491578,Cookie,2.0,1.0,2.0,NaN,NaN,2023-02-23,February
45,TXN_5455792,Salad,3.0,5.0,15.0,Cash,NaN,2023-03-22,March
46,TXN_8078640,Juice,4.0,3.0,12.0,Digital Wallet,In-store,2023-11-03,November
47,TXN_9499313,Juice,5.0,3.0,15.0,NaN,NaN,2023-03-02,March
48,TXN_8201146,Juice,5.0,3.0,15.0,Cash,NaN,2023-06-26,June
49,TXN_8230936,Cake,3.0,3.0,9.0,NaN,NaN,2023-05-02,May